---
title: "Lec 1"
author: "sbsambado"
date: "12/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)

np_visits <- read_csv("National Parks Visitation Data.csv")

```

Explore the data
```{r}

names(np_visits)
dim(np_visits)
class(np_visits)
head(np_visits)
tail(np_visits)

Reg <- np_visits$Region

MaxVis <- max(np_visits$Visitors, na.rm = TRUE)
```


Basic data wrangling (dplyr)
```{r}


df1 <- select(np_visits, State:YearRaw) # only select columns from state through yearraw, store as new data frame df1

df2 <- filter(df1, State == "CA" & Type == "National Park" & YearRaw >= 1950) # filter to retain rows that are CA and NP

df3 <- arrange(df2, Code, YearRaw) # arrange in alphabetical order in Code, THEN by ascending value in Year Raw
#View(df3)

df4 <- mutate(df3, kVis = Visitors/1000) # add new column to df3, ocnverts to units of 1000s of visitors

#View(df4)

df5 <- filter(df4, YearRaw != "Total") # remove 'total' values in the YearRaw column (!= does NOT match)

summary(df5) # we need to change year to numeric vs character

df5$YearRaw <- as.numeric(df5$YearRaw)
class(df5$YearRaw)
```


Intro to piping
```{r}

# %>% (command + shift + m) is saying "and then..."

utah_np <- np_visits %>% 
  filter(State == "UT", Type == "National Park") %>% 
  select(Name, Visitors, YearRaw) %>% 
  filter(YearRaw != "Total") %>% 
  mutate(mill_vis = Visitors/1000000)

utah_np
```

Graph it!
```{r}


VisitorGraph <- ggplot(df5, aes(x = YearRaw, y = kVis)) +
  geom_point()

quartz()
VisitorGraph

VisitorGraph2 <- ggplot(df5, aes(x = YearRaw, y = kVis)) +
  geom_point(aes(color = Code)) +
  geom_line(aes(color = Code)) +
  ggtitle("CA NP Visitations\n1950 - 2016") +
  xlab("\nYear")+ # \n just adds a blank line before this label
  ylab("Thousands of Visitors\n") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(color = "black")) +
  scale_x_continuous(breaks = c(1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020))

quartz()
VisitorGraph2


VisBoxplot <- ggplot(df5, aes(x = Code, y = kVis)) +
  geom_boxplot(aes(fill = Code)) +
  theme_bw() +
  ggtitle("CA NP Visits") +
  xlab("NP") +
  ylab("number of visitors") +
  scale_x_discrete(breaks = c("CHIS","DEVA","JOTR","KICA","LAVO","PINN","REDW","SEQU","YOSE"), 
                   labels = c("Channel Islands","Death Valley","Joshua Tree","Kings Canyon","Lassen Volcanic","Pinnacles","Redwoods","Sequoia","Yosemite")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45))
```

Let's use an interactive graph
```{r}
library(plotly)

ggplotly(VisitorGraph2)
```

